### ISSUE TITLE
Anhang: Einfügen von mehrseitigen Bildern/PDF-Dateien

### ISSUE THREAD

**Issue by LordofAgents** [RvNovae/dhge-latex#101]
Hey ihr, eine kurze Frage:
Wie bewerkstellige ich am besten das Einfügen eines mehrseitigen PDF-Dokumentes in den Anhang? Ich probiere mit /begin{figure} sowie /includegraphics und /includepdf Rum, da habe ich aber das Problem, dass ich jede Seite manuell einfügen muss, und, wenn ich die Unterschrift erst unter der letzten Seite haben möchte, der Link im Anhangsverzeichnis auch auf die letzte Seite zeigt (und nicht auf die erste).

Sorry fürs komplizierte Erklären, aber habt ihr ne Idee?

**Comment by photovoltex** [comment]
```latex
\usepackage{pdfpages}
\includepdf[pages=-]{../<pdfname>.pdf}
```
Hiermit kannst du eine komplette PDF einbinden. 

Wiederum ist es leicht limitiert. Zum Beispiel wird es in einer `figure` env auf eine Seite gequetscht.

**Comment by LordofAgents** [comment]
Dankeschön, ich hab es dadurch gelöst bekommen.
