### ISSUE TITLE
Untersuchung Font Warnings

### ISSUE THREAD

**Issue by RvNovae** [RvNovae/dhge-latex#108]
![image](https://user-images.githubusercontent.com/11728465/144867003-c0d6a944-6694-4449-9ad0-a8703ddbc338.png)

Die in dem Screenshot aufgeführten Warnings sollten mal untersucht und, wenn möglich, behoben werden.

**Comment by emkZero** [comment]
Ursache: Manche Fonts sind in manchen Shapes nicht verfügbar. 

Konkret bedeutet die Fehlermeldung also, dass Bera Serif (`fve`) in der `OT1`-Kodierung nichts für das `medium`-Gewicht ("series") in der normal-Shape `n` anbietet und deshalb mit Computer Modern `cmr` ersetzt wurde.

Den Fehler finde ich seltsam, zumal der Font ja letztendlich funktioniert. Deuten kann ich das aktuell leider nicht.

Edit: [Quelle Kawelle](https://www.latex-project.org/help/documentation/fntguide.pdf)
