### ISSUE TITLE
Extra Ordner für den Fließtext

### ISSUE THREAD

**Issue by RvNovae** [RvNovae/dhge-latex#11]
Vielleicht `main` directory mit `main` file

**Comment by photovoltex** [comment]
willst du dann da einen Ordner wo die Dateien ausgelesen werden?

**Comment by RvNovae** [comment]
Jo also, die ganzen Tex files, die den eigentlich Inhalt haben, sollen gebündelt sein.
Das mischt sich sonst alles so, mit config und abkurz und so.

Da lässt sich aber drüber diskutieren :D
