### ISSUE TITLE
Change float default in dhgefigure

### ISSUE THREAD

**Issue by RvNovae** [RvNovae/dhge-latex#114]
Ich bin mittlerweile nicht mehr so wirklich ein Freund von `H`-Figures.
Deswegen würd ich mal den `H` Default von dem `dhgefigure` Befehl entfernen.

Meinungen dazu hör ich mir gerne an.

- [x] update command
  - [x] `center` -> `centering`
- [x] update snippet

**Comment by emkZero** [comment]
Hmm bin kein Experte, deshalb frag ich mal, ob ich [das](https://de.overleaf.com/learn/latex/Positioning_of_Figures) so richtig verstanden habe. Float bewirkt, dass:

- Bilder nicht inline platziert werden
- nicht über Seitengrenzen hinweg platziert werden

korrekt? In dem Falle habe ich die eigentlich ganz gern.

Edit: oder geht es dir um das große ``H`` spezifisch? Ich persönlich bevorzuge ``h``

**Comment by RvNovae** [comment]
Es geht um `H`, genau.

LaTeX sollte entscheiden, wo die Bilder hinkommen und nicht der Nutzer.
Nur in Einzelfällen sollte man die Position bspw. mit `b` oder `t` abändern müssen.
Deswegen sollten wir den default für den parameter vielleicht auf `tbp` oder so setzen. 

Oder empfiehlt jemand einen besseren Default?
Vielleicht lieber ``!htb` 🤔

**Comment by emkZero** [comment]
Boah schwierig. `tbp`, also die Standardoption sieht gut aus, `htb` aber auch. `p` würde ich persönlich in jedem Falle doof finden.

Da `com.tex` eh nach `config.tex` geladen wird, könnte man das auch konfigurierbar machen. Im Internet findet man Befürworter beider Varianten.

Ach und da wir schonmal in den Codezeilen sind: das center-Environment kann man ablösen mit einem `\centering`
Edit: das wär mir jetzt keine eigene PR wert, aber kann man ja mit aufnehmen

**Comment by RvNovae** [comment]
> Da `com.tex` eh nach `config.tex` geladen wird, könnte man das auch konfigurierbar machen. Im Internet findet man Befürworter beider Varianten.

Den Vorschlag hat Felix auch schon gebracht ... vielleicht ist das gar keine so schlechte Idee. Dann müssten wir trotzdem einen Standard definieren. Wenn niemand was gegen `tbp` hat, würd ich dafür sein.

> Ach und da wir schonmal in den Codezeilen sind: das center-Environment kann man ablösen mit einem `\centering` Edit: das wär mir jetzt keine eigene PR wert, aber kann man ja mit aufnehmen

Das ist eine gute Idee.

**Comment by emkZero** [comment]
Nach einigem Probieren war es doch nicht so einfach, die Standardposition konfigurierbar zu machen. Deshalb haben wir gekniffen und uns auf tbp geeinigt.
