### ISSUE TITLE
Was zur Hölle ist mit den Fonts los?

### ISSUE THREAD

**Issue by emkZero** [RvNovae/dhge-latex#122]
In Wahrheit scheint das Template mit `CFANCYFONTS 1` nicht Bera, wie gedacht, sondern `mathpazo` zu verwenden, weil es nach `beraserif` geladen wird.

Der Coding-Aufwand beschränkt sich mMn auf kleine Aufräum-Arbeiten, da wir ja Palladio-L-Roman (mathpazo) fälschlicherweise für Bera gehalten haben.

Mein Lösungsvorschlag:

- [x] ``beraserif`` entfernen
- [x] prüfen, ob ``berasans`` gebraucht wird und ggf. entfernen
- [x] In der Doku vermerken, dass Palladio / Palatino verwendet wird

P.S.: Danke an Prof. Kusche für den Hinweis. Darauf wären wir wahrscheinlich nie von alleine gekommen 😅

**Comment by RvNovae** [comment]
Die Vorgehensweise klingt sinnvoll 👍

**Comment by RvNovae** [comment]
Ich habe übrigens [hier](https://tex.stackexchange.com/questions/504366/how-to-use-palatino-font-for-text-and-what-about-maths) gelesen, dass man `mathpazo` nicht explizit inkludieren soll, sondern über `\usepackage{newpxtext,newpxmath}` holen sollte.
Das scheint auch recht gut zu funktionieren.
