### ISSUE TITLE
Doku-Eintrag zum Konfigurieren der VS-Code LaTeX-Workshop Extension

### ISSUE THREAD

**Issue by RvNovae** [RvNovae/dhge-latex#21]
Sobald man weiß, wie man alles einstellen will, sollte das eigentlich gar nicht _so_ schwierig sein.

Hauptsächlich erstmal so Sachen wie Build Prozesse.

Aber das kann erstmal noch warten 😄

**Comment by photovoltex** [comment]
interessanterweise musst du wenig ändern dies bezüglich... 

JSON:
strg + shift + p -> "Preferences: Open Settings (JSON)"
hier kannst du simple Sachen konfigurieren wie z.B. deine Output PDF angezeigt werden soll oder wann deine .tex Datei gebaut werden soll 

klicki bunti:
kann man auch einfach unter File->Preferences->Settings anpassen -> unter Extensions -> Latex

sollte eigentlich als config reichen... das ist ja nicht für das Template wichtig, oder?

**Comment by RvNovae** [comment]
Ja das stimmt schon. Wahrscheinlich ists besser einfach stattdessen eine kleine Anleitung in die Doku zu packen.
