### ISSUE TITLE
Anlagen-, Literatur-und Abkürzungsverzeichnis nur anzeigen, wenn Einträge vorhanden

### ISSUE THREAD

**Issue by RvNovae** [RvNovae/dhge-latex#28]
Ähnlich Abbildungs- und Tabellenverzeichnis

- [x] Anlagenverzeichnis
- [x] Literaturverzeichnis
- [x] Abkürzungsverzeichnis

**Comment by LordofAgents** [comment]
Könnten wir bitte den Branch einmal aktualisieren, damit die Änderungen vom Main mit drin sind? Ist sonst doof, wenn das `acro`-Package nicht drin ist

**Comment by photovoltex** [comment]
push am besten auf [verzeichnisse-nur-mit-inhalt-anzeigen](https://github.com/RvNovae/dhge-latex/tree/verzeichnisse-nur-mit-inhalt-anzeigen)
ich werd heute nachmittag noch meine Änderungen nachziehen^^

**Comment by LordofAgents** [comment]
Perfekt danke!
