### ISSUE TITLE
automatisiertes testen neuer und bestehender Funktionen 

### ISSUE THREAD

**Issue by photovoltex** [RvNovae/dhge-latex#45]
### Grundgedanke
Da die aktuelle "Continuous Integration" nur den Bau des Templates garantiert, sollte für die neuen und schon vorhanden Funktionen ein, gleichzeitig beispielhaftes, Testdokument gebaut werden.
Dieses soll die Funktionalität der eigenen implementierten Funktionen garantieren.

### Vorschlag:
einen Ordner erstellen welcher ein komplett fertiges Projekt kompiliert.
Dieser soll folgendes enthalten:
- [ ] alle Funktionen welche in einem Projekt verwendet werden sollen/können, diese sollen in den entsprechenden .tex Dateien beispielhaft eingefügt werden.
-  aktuell `\dhgefigure{<datei>}{<options>}{<caption>}{<label>}`, `\anlagen{<type>}{<flag>}`, `\doubleunderline{<word>}`

Hier muss man zwischen Funktionen unterscheiden, welche das erstellen des Templates vereinfachen und Funktionen die das schreiben der Projektarbeiten vereinfachen. ( Siehe com.tex -> `\markBox{<number>}` )

**Comment by RvNovae** [comment]
Man könnte eine `tests.tex` datei einfügen, die in die main.tex geschrieben wird. (Das sollte über die linux shell sehr einfach gehen) Dann wird gebaut. Somit bleibt die main.tex frei von Müll und trotzdem kann alles getestet werden.

**Comment by RvNovae** [comment]
Weitere idee: ein `tests` ordner, von dem aus dann `main.tex` und `anlagen.tex`, und in Zukunft weitere testfiles kopiert werden können.

**Comment by photovoltex** [comment]
les dir mal meinen Vorschlag durch :P

**Comment by RvNovae** [comment]
quatschen wir dann nachher drüber
