### ISSUE TITLE
Abkürzungsverzeichnis ist nicht alphabetisch sortiert 

### ISSUE THREAD

**Issue by photovoltex** [RvNovae/dhge-latex#60]
Wie der Title schon sagt ist das Abkürzungsverzeichnis nicht erwartungsgemäß sortiert.
Dies kann beim Leser Verwirrung stiften wenn dieser nach einer Abkürzung sucht.

Tasks:
- [x] package austauschen
- [x] wiki updaten
- [x] `abk.tex` updaten
- [x] Sortierung konfigurieren

**Comment by photovoltex** [comment]
siehe https://tex.stackexchange.com/a/29352

**Comment by LordofAgents** [comment]
Ich hab mir das ganze einmal angeschaut, man könnte auf das `acro`-package umsteigen. Das Bedienen im Text ist da ja dasselbe, allerdings ändert sich das Deklarieren der Abkürzungen in `abk.tex`. Würde entsprechend auch die Abwärtskompatibilität zu Dokumenten, die älter sind, zerstören. Wollen wir das trotzdem in Kauf nehmen?
Sonst könnte man evtl. auch fleißig Alias-Commands, ähnlich wie `\dhgefigure` schreiben. Wäre ein höherer Aufwand.

**Comment by RvNovae** [comment]
Ahh sorry, hab vor lauter Klausuren ganz vergessen zu antworten.

Ich glaube der Verlust der Abwärtskompatibilität wäre kein großes Problem. Aus meiner Erfahrung updated man sein Dokument später eh nicht mehr ... und wenn doch, muss man die Definitionen halt umbiegen, das wird schon irgendwie machbar sein.

Ich wäre demnach dafür auf das `acro` package umzusteigen. 

Man müsste ja lediglich:

- [ ] package austauschen
- [ ] wiki updaten
- [ ] `abk.tex` updaten
- [ ] Sortierung konfigurieren

Wenn du Lust hast, kannst du gerne einen PR einreichen @LordofAgents, ansonsten würden @photovoltex und ich uns das nach unserer mündlichen Praxisprüfung mal anschauen. Vorher wird das wahrscheinlich eher nichts bei uns 😅

**Comment by LordofAgents** [comment]
Ich würde mich um den PR kümmern, hänge aber gerade auch in der Klausurenphase. Ich schaue, dass ich mich drum kümmere.

**Comment by photovoltex** [comment]
Hey @LordofAgents, 
wenn du dich darum kümmerst könntest du dann auch mal schauen ob es einen Möglichkeit gäbe zu zählen wie viele Einträge das Verzeichnis hat. Bezieht sich auf #28. Falls du willst kannst du auch gleich ähnlich wie https://github.com/RvNovae/dhge-latex/commit/d33f7323dd74761ff26b1a5ccb33be61af8f1393 einen commit auf der zugehörigen Branch hinterlassen.
Gib mir dann nochmal Rückmeldung ob dir das so passt^^ (Zeit spielt relativ keine Rolle insofern es gemacht wird (´• ᴗ •̥`))

**Comment by LordofAgents** [comment]
Ich dachte, ich hätte geantwortet, sorry dafür, ich schaue was ich tun kann. Sobald ich wieder etwas Luft habe, kümmere ich mich drum

**Comment by RvNovae** [comment]
Mach dir keinen Stress, das Studium ist schon stressig genug 😄

**Comment by LordofAgents** [comment]
Moin, ich melde mich mal wieder. 
Ich scheitere beim Umstellen. Der zeigt das Verzeichnis irgendwie nur an, wenn ich bei `\printacronyms` die Argumente `[display=all, heading=none]` hinzufüge. Dann ist das aus mir nicht ersichtlichen Gründen im Inhaltsverzeichnis nicht drin, und Abkürzungen werden dann immer angezeigt, egal ob verwendet oder nicht. Ich hab das ganze in mein Fork gepusht, kann bitte einer von euch, wenn ihr Zeit habt, mal drüber schauen?

**Comment by RvNovae** [comment]
Hi, ich werde es mir wahrscheinlich am Wochenende mal anschauen.
@photovoltex meinte, dass er es sich auch die Tage mal anschauen will.

Wir melden uns dann :)

**Comment by photovoltex** [comment]
Hey^^ @LordofAgents, hatte gerade mal drüber geschaut (´• ᴗ •̥\`)
Hatte erst mit den globalen Einstellungen des Packages rumgespielt. Damit war das Problem allerdings noch nicht gelöst :( ´◦ω◦｀):.

Die eigentliche Lösung deines Problems ist wo die acros importiert werden. Wenn ich diese nach der `config.tex` importiere funktioniert es und meine globalen settings wurden auch angewand.

Hoffentlich fkt es auch bei dir
_das Package hat auf jedenfall viel Potenzial ( ´◔ ω◔`)_

**Comment by RvNovae** [comment]
> Hey^^ @LordofAgents, hatte gerade mal drüber geschaut (´• ᴗ •̥`)
> Hatte erst mit den globalen Einstellungen des Packages rumgespielt. Damit war das Problem allerdings noch nicht gelöst :( ´◦ω◦｀):.
> 
> Die eigentliche Lösung deines Problems ist wo die acros importiert werden. Wenn ich diese nach der `config.tex` importiere funktioniert es und meine globalen settings wurden auch angewand.
> 
> Hoffentlich fkt es auch bei dir
> _das Package hat auf jedenfall viel Potenzial ( ´◔ ω◔`)_

Ich glaube Felix meint _vor_ `config.tex`:

```tex
\input{abk.tex}
\input{../config.tex}
```

Dann funktioniert es bei mir auch. 
Die selbstgebastelte Überschrift müsste man noch rausnehmen (sonst hat man zusätzlich eine leere Akürzungsseite).
Anscheinend bringt `acro` die selbst mit. 

Anscheinend ist acro aktuell so konfiguriert, dass die Überschrift `Akürzungen` und nicht `Abkürzungsverzeichnis` heißt.
Wie ist da die öffentliche Meinung dazu? Wollen wir das so lassen oder das wieder auf `Abkürzungsverzeichnis` ändern?

**Comment by LordofAgents** [comment]
Vielen Dank für eure Hilfe, ich hab das ganze jetzt implementiert und mach gleich nen PR auf. 😄 
Ich habe das ganze jetzt Abkürzungsverzeichnis genannt, kann man ja schnell in der `setup.tex` ändern.
Schaut mal bitte drüber, ob das passt, ich hoffe, ich hab nichts übersehen.

**Comment by photovoltex** [comment]
Hey @LordofAgents, dann bitte die Änderungen bezüglich ausblenden wenn nicht genutzt, insofern du eine Möglichkeit findest, mit #28 verknüpfen bzw. daran dann schreiben vielen danke^^

**Comment by LordofAgents** [comment]
@photovoltex Ich versteh dich nicht ganz, welche Änderungen soll ich denn wieder ausblenden?
Um #28 kümmere ich mich noch drum, hab ich bereits oben mehrmals geschrieben.

**Comment by photovoltex** [comment]
War nur als reminder gemeint, nix weiter^^
