### ISSUE TITLE
weitere Angaben auf dem Deckblatt

### ISSUE THREAD

**Issue by ndegel** [RvNovae/dhge-latex#67]
Es wäre schön auf dem Deckblatt auch die Anschrift des Ausbildungsbetriebs (siehe Hinweise der DHGE, Anhang A2) und einen zweiten Betreuer (zB in PA4 ein Betreuer vom Unternehmen und ein Betreuer von der DHGE) angeben zu können.

**Comment by RvNovae** [comment]
Das gehört m.E. zur Bachelorarbeit, siehe: https://github.com/RvNovae/dhge-latex/issues/4

**Comment by ndegel** [comment]
Ja bei der Unternehmensanschrift ist es nicht klar definiert, aber in der PA4 hat man auch zwei Betreuer. Lässt sich das schon in der aktuellen Version umsetzen beide anzugeben?

**Comment by RvNovae** [comment]
Ah okay, interessant 🤔 

Theoretisch lässt sich das Deckblatt (und auch alles andere) ohne weiteres anpassen.
Einfach in `/build/components/deckblatt.tex` im Betreuer tabular noch eine zweite Zeile hinzufügen. 

Beispiel für den angepassten Block:

```latex
\begin{tabular}{rl}
	\hspace{0.45\textwidth} &          \\
	   Betreuer: & \CBETREUER \\
	   & Betreuer 2
\end{tabular}
```

Danach sollte man natürlich die update scripte nicht mehr ausführen, sonst werden die Änderungen überschrieben 😄 
Der Betreuer 2 lässt sich analog zum ersten Betreuer natürlich auch in eine Variable auslagern 😉

**Comment by RvNovae** [comment]
Die Adresse lässt sich auch einfach hinzufügen, indem du einen neuen `tabular` Block an eine geeignete Stelle in `build/components/deckblatt.tex` packst.

```latex
\begin{tabular}{rl}
	\hspace{0.45\textwidth} &          \\
	Anschrift: & Straße \\
	& PLZ  \\
	& Stadt \\
	& usw. \\
\end{tabular}
```

**Comment by ndegel** [comment]
Alles klar, danke. So ähnlich hatte ich es jetzt auch schon angepasst. Dachte es geht vielleicht schöner, dass man zum Beispiel die gesamte Adresse in einer Variable speichern kann.

**Comment by RvNovae** [comment]
> Alles klar, danke. So ähnlich hatte ich es jetzt auch schon angepasst. Dachte es geht vielleicht schöner, dass man zum Beispiel die gesamte Adresse in einer Variable speichern kann.

Bin mir nicht sicher.
Du kannst ja mal versuchen die Anschrift mitsamt `\\` und `&` Zeichen in eine Variable zu speichern. 

Aber im Endeffekt muss man die Stelle ja nicht zum Glück nicht so oft anfassen 😅

**Comment by ndegel** [comment]
> Du kannst ja mal versuchen die Anschrift mitsamt `\\` und `&` Zeichen in eine Variable zu speichern.

Ich hatte es mit `\newline` versucht, aber da wurde der Zeilenumbruch ignoriert.

**Comment by RvNovae** [comment]
Ah okay.

Habe gerade mal getestet.
Mit 
```latex
\def\ANSCHRIFT      {& Straße \\ & PLZ etc. \\ & test \\ & test \\}
```
für die Variablendeklaration und 
```latex
\begin{tabular}{rl}
	\hspace{0.45\textwidth} &          \\
	Anschrift: \ANSCHRIFT
\end{tabular}
```
für den Anschriftsblock funktioniert es bei mir.

![image](https://user-images.githubusercontent.com/11728465/102018191-02f05800-3d6c-11eb-9713-182de5886f5b.png)
