### ISSUE TITLE
Paketdeklaration footmisc: Fußnoten jede Seite neubeginnen?

### ISSUE THREAD

**Issue by LordofAgents** [RvNovae/dhge-latex#74]
Moinsen, ich hab mir mal erlaubt, das Template mitzunutzen und finde eure Arbeit super. 
Mir ist bei der Paketdefinition von `footmisc` (in der `package.config.tex`) aufgefallen, dass ihr das Argument `perpage` nutzt, was ja bei jeder Seite die Fußnoten neubeginnt. Das entspricht nicht ganz den Anforderungen der DHGE. Habt ihr euch was dabei gedacht? Sonst würde ich nen Pullrequest machen, um das rauszunehmen.

Danke schonmal!

**Comment by RvNovae** [comment]
Hi, freut uns, dass es dir hilft!

Ich glaub das hatte ursprünglich mal was mit unserem `\footcite` Zitationsstil zu tun. 
Denke das kann raus. In dem Rahmen könnte man den neueren `\supercite` Zitationsstil mal gescheit dokumentieren.

Wenn du einen PR machst, dann ersetze mal bitte gleich den gesamten Inhalt von `main.tex` mit Folgendem:

```latex
\section{Erstes Kapitel im Hauptteil}
Text mit Fußnoten-Style-Zitat\footcite{Xarticle}

Text mit Super-Style-Zitat\supercite{Xarticle}

Hier kommt eine Abkürzung: \ac{dhge}
```

Da wäre ich dir sehr dankbar!
