### ISSUE TITLE
CI reparieren

### ISSUE THREAD

**Issue by RvNovae** [RvNovae/dhge-latex#76]
DockerHub -> rate limiting
travis -> domain wechsel

Vielleicht direkt als Github Action umsetzen. 
Direkt für die main branch umsetzen (https://github.com/RvNovae/dhge-latex/issues/79 berücksichtigen)

- [x] bei PR auf main einmal durchbauen (mit tests)
- [x] bei merge auf main einmal durchbauen (mit tests)

**Comment by photovoltex** [comment]
siehe [LaTeX compilation](https://github.com/marketplace/actions/github-action-for-latex) ([Beispiel](https://dev.to/mrturkmen/latex-with-github-actions-4580))
