### ISSUE TITLE
repo aufräumen

### ISSUE THREAD

**Issue by RvNovae** [RvNovae/dhge-latex#79]
Ich würd mal folgendes vorschlagen:

- [x] `master` branch wegwerfen
- [x] `develop` in `main` umbenennen
- [ ] update scripts anpassen
- [x] orga fork action anpassen

**Comment by emkZero** [comment]
![image](https://user-images.githubusercontent.com/26359277/124484974-5c71b000-ddac-11eb-98b9-11f10424baa7.png)
