### ISSUE TITLE
Indirektes Zitieren dokumentieren

### ISSUE THREAD

**Issue by emkZero** [RvNovae/dhge-latex#80]
Für mich als Anfänger wäre es schön, wenn in der Wiki steht, wie man richtig indirekt zitiert.

Der richtige Syntax scheint zu sein: ``\footcite[Vgl.][]{Computerphile.2020}``

**Comment by emkZero** [comment]
Ich hätte ja ein PR gemacht, aber das habe ich für die Wiki nicht gefunden. Scheint nicht vorgesehen zu sein

**Comment by RvNovae** [comment]
https://github.com/RvNovae/dhge-latex/issues/81
