### ISSUE TITLE
Command-Ideen: Codebox und Todo

### ISSUE THREAD

**Issue by emkZero** [RvNovae/dhge-latex#84]
Ich habe mir hier was gebastelt, sprich von StackOverflow abgeschrieben, was aktuell in meiner preamble.tex lebt:

```latex
\usepackage{tikz}

\newcommand*{\codeinline}[1]{\tikz[baseline=(X.base)]
	\node[fill=black!10] (X) {#1};}

\newcommand*{\todo}[1]{\tikz[baseline=(X.base)]
	\node[fill=red!42] (X) {#1};}
```

Der erste Command markiert Text grau, sodass er zumindest spartanisch an ne Codebox erinnert (funktioniert so nur inline).

Der zweite Command markiert Text rot und etwas stärker, sodass man seine Todos leichter finden kann.

Wäre das auch interessant für Andere?

**Comment by emkZero** [comment]
Oh das könnte btw vielleicht eher ne Conversation als ein Issue sein 🤔 

Wobei ich auch nie weiß, was ich jetzt wohin schreiben soll

**Comment by RvNovae** [comment]
Hm, ich persönlich hätte da nicht so wirklich eine Verwendung dafür.
Für inline krams nehm ich meist einfach `\texttt{}` und für Code-Blöcke das Minted package.

TODOs regle ich über vscode und finde ich eigentlich auch empfehlenswerter, das über den Editor zu machen. 

Ansonsten danke für den Vorschlag.

**Comment by emkZero** [comment]
> Hm, ich persönlich hätte da nicht so wirklich eine Verwendung dafür.
> Für inline krams nehm ich meist einfach `\texttt{}` und für Code-Blöcke das Minted package.
> 
> TODOs regle ich über vscode und finde ich eigentlich auch empfehlenswerter, das über den Editor zu machen.
> 
> Ansonsten danke für den Vorschlag.

Ah, alles klar. Die Packages werd ich mir mal ansehen.

Schreiben tu ich in Texstudio, aber bin so konfus, dass Todos ZUSÄTZLICH zu meinen Notizen auch in der Reinschrift landen. Wo ich das so schreibe... mega dumm eigentlich
