### ISSUE TITLE
Update readme: Verweis auf vscode recommended Extension

### ISSUE THREAD

**Issue by photovoltex** [RvNovae/dhge-latex#92]
Es soll ein Verweis auf die recommended Extension für vscode in der readme/doku erwähnt werden.

Wenn in den Extension nach `@recommended` gesucht wird, werden alle recommended Extension angezeigt.
Auch ist dies der fall wenn man das repo in code öffnet in der unteren rechten Ecke

evtl. Bild hinzufügen 
![recommended](https://user-images.githubusercontent.com/36958734/125598611-086a7491-b701-4ca5-9d48-8c6b599c55ba.png)

**Comment by emkZero** [comment]
Ich verwende einen anderen Linter: ``davidanson.vscode-markdownlint``

![image](https://user-images.githubusercontent.com/26359277/125613277-30864afa-2bac-46c0-989d-2f2a2e789f73.png)

Evtl könnte für den ja auch eine Konfiguration aufgenommen werden?
